### ISSUE TITLE
Trying to Create Instance of Abstract Class

### ISSUE THREAD

**Issue by ab-tools** [msawczyn/EFDesigner#171]
When you have an inheritance relation in the DB schema with the parent class marked as abstract it still creates a `CreateItemUnsafe` method trying to instance this abstract class which obviously results in a compilation error.

Tested with v2.0.0.4.

**Comment by msawczyn** [comment]
Thanks for that. I had also found that a few days ago. Fixed for the release.

**Comment by ab-tools** [comment]
Thanks a lot, I can confirm this works with with the release v2.0.0 correctly now!
