### ISSUE TITLE
OneToMany relation issue since upgrade to 1.2.6.23 with CS0102

### ISSUE THREAD

**Issue by tomsedi** [msawczyn/EFDesigner#51]
Hi,

I today upgraded to version 1.2.6.23 (from 1.2.6.21 I believe). Since then I have an issue with one of my relations which worked fine before.
`
<unidirectionalAssociation Id="c4bfc1af-ccf6-4dfd-955c-489f6acf160f" sourceMultiplicity="ZeroMany" targetMultiplicity="One" targetPropertyName="Artikel" collectionClass="HashSet" sourceRole="Dependent" targetRole="Principal" foreignKeyLocation="None">
           <modelClassMoniker Id="65a01e60-c158-4eaf-a9d9-4f1178f3699f" />
</unidirectionalAssociation>
`

This generates the definition of `Artikel` two times:

`      protected Backend.Data.Artikelstamm Artikel;` 
and

`      public Backend.Data.Artikelstamm Artikel
      {
         get
         {
`
which causes an error CS0102.

Did I do something wrong in the past or is this an issue with the new version? Thanks.

**Comment by msawczyn** [comment]
Spot on. Seems that `implementNotify` had issues (as did the regression tests this week). Fixed in 1.2.6.25.
