### ISSUE TITLE
Compilation Error after Upgrading to v1.3.0.11

### ISSUE THREAD

**Issue by ab-tools** [msawczyn/EFDesigner#129]
I've upgraded from v1.3.0.4 to v1.3.0.11 and now get a compilation error due to following automated generated code change.

Previous line:
`modelBuilder.Entity<global::QuickArchive.Data.Db.Keyword>().HasIndex(t => t.Name)`
New line:
`modelBuilder.Entity<global::QuickArchive.Data.Db.Keyword>().HasIndex("_Name")`
When I change this back manually compilation works fine again.

And that's the property definition the code is generated from:
![image](https://user-images.githubusercontent.com/1347603/69912655-b5d56880-142c-11ea-967c-8ef59f2bbf19.png)

What's the reason for this code change that leads to a compilation error?

**Comment by msawczyn** [comment]
It's a bug in the EFCore generation that's not present in the EF6 version, but since this isn't an AutoProperty it shouldn't be doing that. There's something else going on here outside of this property. If you would, please take a look at `EFCoreDesigner.ttinclude` around line 304. Change
```
         segments.Add($"modelBuilder.Entity<{modelClass.FullName}>().HasIndex(t => t.{indexed.Name})");
```
to
```
         segments.Add(indexed.AutoProperty
                  ? $"modelBuilder.Entity<{modelClass.FullName}>().HasIndex(t => t.{indexed.Name})"
                  : $"modelBuilder.Entity<{modelClass.FullName}>().HasIndex(\"_{indexed.Name}\")");
```
and see if that changes things.

Thanks for the report.

**Comment by ab-tools** [comment]
First thanks a lot for your really fast reply on a Sunday! :-)

I'm targeting .NET 4,7.2 at the moment, so I would say it's EF6 (sorry, should have mentioned that from the beginning) - therefore I don't think this it can be related to the EFCore generation?

Still tried to do the change you suggest, but without effect which I expected, because I guess it's rather `EF6Designer.ttinclude` what is used and not `EFCoreDesigner.ttinclude`.

Please let me know in case you need any further info on this from myself!

**Comment by msawczyn** [comment]
Hmm. Then that makes less sense. Since `AutoProperty` is set to false, `_Name` shouldn't even exist. Would you be able to post a minimal repro model that shows this problem?

**Comment by ab-tools** [comment]
Yes as I can even reproduce the problem with just a single entity in this project:
[EFDesignerTest.zip](https://github.com/msawczyn/EFDesigner/files/3910862/EFDesignerTest.zip)
